window.ANIME_RIFT_DATA = {
  title: "Neon Rift Tactics",
  subtitle: "Anime tactical battler with animated skills, gacha, PvP, and campaign progression",
  maxSquadSize: 3,
  maxBenchSize: 6,
  portraitSheet: "./assets/anime-pack-sheet.png",
  battleBackground: "./assets/anime-battle-bg.png",
  vfxSheet: "./assets/vfx-sheet.png",
  currencies: {
    credits: 1800,
    gems: 640,
    tickets: 4,
    rank: 1200
  },
  heroes: [
    {
      id: "rin",
      name: "Rin Aoi",
      callsign: "Crimson Edge",
      role: "Striker",
      rarity: "SSR",
      portrait: 0,
      element: "Void",
      color: "magenta",
      base: { hp: 1120, atk: 168, def: 48, spd: 98, mana: 12 },
      skills: ["neon_slash", "afterimage_step", "phase_burst", "eclipse_rush"],
      passive: "Rin gains Focus when an ally shields or heals; next strike deals bonus true damage.",
      bio: "Frontline blade specialist who chains movement into a second hit.",
      faction: "Rift Vanguard"
    },
    {
      id: "gale",
      name: "Gale Ryu",
      callsign: "Iron Rampart",
      role: "Guardian",
      rarity: "SSR",
      portrait: 1,
      element: "Steel",
      color: "red",
      base: { hp: 1460, atk: 138, def: 74, spd: 76, mana: 10 },
      skills: ["shield_rush", "bulwark_field", "counter_bash", "citadel_drop"],
      passive: "When Gale is targeted, nearby allies gain a small barrier.",
      bio: "Tank unit that can shove enemies back and anchor the team.",
      faction: "Rift Vanguard"
    },
    {
      id: "lyra",
      name: "Lyra Vale",
      callsign: "Signal Witch",
      role: "Hacker",
      rarity: "SR",
      portrait: 2,
      element: "Flux",
      color: "cyan",
      base: { hp: 980, atk: 152, def: 40, spd: 104, mana: 14 },
      skills: ["signal_bolt", "chain_scramble", "system_break", "overclock_surge"],
      passive: "Hack effects extend one extra turn if the target is already debuffed.",
      bio: "A control specialist that jams enemy tempo and lights up the lane.",
      faction: "Data Choir"
    },
    {
      id: "yuna",
      name: "Yuna Kisaragi",
      callsign: "Deadeye Blue",
      role: "Sniper",
      rarity: "SR",
      portrait: 3,
      element: "Ice",
      color: "blue",
      base: { hp: 1020, atk: 176, def: 36, spd: 92, mana: 11 },
      skills: ["deadeye_round", "piercing_line", "focus_lock", "zero_hour"],
      passive: "Yuna's critical rate rises when she attacks the healthiest enemy.",
      bio: "Long-range burst shooter with precise lane control.",
      faction: "Aster Unit"
    },
    {
      id: "mina",
      name: "Mina Hoshino",
      callsign: "Bloom Circuit",
      role: "Medic",
      rarity: "SR",
      portrait: 4,
      element: "Life",
      color: "green",
      base: { hp: 1090, atk: 128, def: 44, spd: 88, mana: 15 },
      skills: ["heal_pulse", "guard_bloom", "cleanse_stream", "life_symphony"],
      passive: "Healing an ally grants them a brief haste buff.",
      bio: "Team sustain and barrier support with fast recovery loops.",
      faction: "Aster Unit"
    },
    {
      id: "kuro",
      name: "Kuro Shiden",
      callsign: "Void Monarch",
      role: "Invoker",
      rarity: "SSR",
      portrait: 5,
      element: "Astral",
      color: "violet",
      base: { hp: 1210, atk: 190, def: 52, spd: 84, mana: 13 },
      skills: ["void_pulse", "gravity_brand", "nightfall_chain", "monarch_judgment"],
      passive: "When Kuro scores a takedown, he gains a bonus action shard.",
      bio: "Late-game closer with the strongest cinematic skills in the roster.",
      faction: "Null Dominion"
    }
  ],
  enemies: [
    {
      id: "raider",
      name: "Street Raider",
      portrait: 1,
      rarity: "N",
      base: { hp: 820, atk: 112, def: 28, spd: 72, mana: 8 },
      skills: ["enemy_burst", "enemy_pressure", "enemy_cover"],
      tone: "aggressive"
    },
    {
      id: "drone",
      name: "Hex Drone",
      portrait: 2,
      rarity: "R",
      base: { hp: 760, atk: 104, def: 22, spd: 86, mana: 9 },
      skills: ["enemy_laser", "enemy_chain", "enemy_shield"],
      tone: "tech"
    },
    {
      id: "assassin",
      name: "Phantom Blade",
      portrait: 3,
      rarity: "SR",
      base: { hp: 900, atk: 142, def: 32, spd: 96, mana: 10 },
      skills: ["enemy_slash", "enemy_mark", "enemy_strike"],
      tone: "swift"
    },
    {
      id: "warden",
      name: "Void Warden",
      portrait: 5,
      rarity: "SSR",
      base: { hp: 1260, atk: 168, def: 48, spd: 80, mana: 11 },
      skills: ["enemy_void", "enemy_brand", "enemy_blast"],
      tone: "boss"
    }
  ],
  skills: {
    neon_slash: {
      id: "neon_slash",
      name: "Neon Slash",
      slot: "A",
      target: "enemy",
      mode: "slash",
      cost: 1,
      cooldown: 0,
      power: 1.1,
      vfx: "slash",
      motion: "dash",
      desc: "Dash in, cut once, and leave a bleed mark."
    },
    afterimage_step: {
      id: "afterimage_step",
      name: "Afterimage Step",
      slot: "B",
      target: "self",
      mode: "buff",
      cost: 1,
      cooldown: 2,
      power: 0,
      vfx: "blink",
      motion: "blink",
      desc: "Gain haste and dodge for the next turn."
    },
    phase_burst: {
      id: "phase_burst",
      name: "Phase Burst",
      slot: "C",
      target: "enemy",
      mode: "projectile",
      cost: 2,
      cooldown: 1,
      power: 1.35,
      vfx: "impact",
      motion: "shot",
      desc: "Fire a piercing burst with bonus damage to marked targets."
    },
    eclipse_rush: {
      id: "eclipse_rush",
      name: "Eclipse Rush",
      slot: "U",
      target: "enemyAll",
      mode: "ultimate",
      cost: 4,
      cooldown: 4,
      power: 1.7,
      vfx: "burst",
      motion: "cinematic",
      desc: "A high-speed opener that hits every enemy and refreshes Focus."
    },
    shield_rush: {
      id: "shield_rush",
      name: "Shield Rush",
      slot: "A",
      target: "enemy",
      mode: "push",
      cost: 1,
      cooldown: 0,
      power: 0.95,
      vfx: "shield",
      motion: "dash",
      desc: "Rush forward, damage the target, and gain barrier."
    },
    bulwark_field: {
      id: "bulwark_field",
      name: "Bulwark Field",
      slot: "B",
      target: "allyAll",
      mode: "shield",
      cost: 2,
      cooldown: 2,
      power: 1,
      vfx: "shield",
      motion: "cast",
      desc: "Raise a protective field for the whole team."
    },
    counter_bash: {
      id: "counter_bash",
      name: "Counter Bash",
      slot: "C",
      target: "enemy",
      mode: "strike",
      cost: 2,
      cooldown: 1,
      power: 1.4,
      vfx: "impact",
      motion: "smash",
      desc: "Strike hard. If attacked last turn, retaliate even harder."
    },
    citadel_drop: {
      id: "citadel_drop",
      name: "Citadel Drop",
      slot: "U",
      target: "allyAll",
      mode: "ultimateShield",
      cost: 4,
      cooldown: 4,
      power: 1.2,
      vfx: "shield",
      motion: "cinematic",
      desc: "Drop a massive defensive aura and heal the weakest ally."
    },
    signal_bolt: {
      id: "signal_bolt",
      name: "Signal Bolt",
      slot: "A",
      target: "enemy",
      mode: "chain",
      cost: 1,
      cooldown: 0,
      power: 1.0,
      vfx: "bolt",
      motion: "zap",
      desc: "Zap the target and bounce to an adjacent foe."
    },
    chain_scramble: {
      id: "chain_scramble",
      name: "Chain Scramble",
      slot: "B",
      target: "enemy",
      mode: "debuff",
      cost: 2,
      cooldown: 1,
      power: 0.9,
      vfx: "bolt",
      motion: "cast",
      desc: "Damage a target and scramble its attack output."
    },
    system_break: {
      id: "system_break",
      name: "System Break",
      slot: "C",
      target: "enemy",
      mode: "pierce",
      cost: 2,
      cooldown: 2,
      power: 1.45,
      vfx: "burst",
      motion: "shot",
      desc: "Pierce through shield and armor with a hard data spike."
    },
    overclock_surge: {
      id: "overclock_surge",
      name: "Overclock Surge",
      slot: "U",
      target: "enemyAll",
      mode: "ultimate",
      cost: 4,
      cooldown: 4,
      power: 1.55,
      vfx: "bolt",
      motion: "cinematic",
      desc: "Flood the battlefield with a chain pulse and stack hack."
    },
    deadeye_round: {
      id: "deadeye_round",
      name: "Deadeye Round",
      slot: "A",
      target: "enemy",
      mode: "projectile",
      cost: 1,
      cooldown: 0,
      power: 1.2,
      vfx: "impact",
      motion: "shot",
      desc: "A clean long-range shot with bonus crit pressure."
    },
    piercing_line: {
      id: "piercing_line",
      name: "Piercing Line",
      slot: "B",
      target: "enemy",
      mode: "pierce",
      cost: 2,
      cooldown: 1,
      power: 1.35,
      vfx: "impact",
      motion: "shot",
      desc: "Line up a beam that ignores shield and cover."
    },
    focus_lock: {
      id: "focus_lock",
      name: "Focus Lock",
      slot: "C",
      target: "self",
      mode: "buff",
      cost: 1,
      cooldown: 1,
      power: 0,
      vfx: "blink",
      motion: "cast",
      desc: "Increase crit chance and move faster on the next action."
    },
    zero_hour: {
      id: "zero_hour",
      name: "Zero Hour",
      slot: "U",
      target: "enemyAll",
      mode: "ultimate",
      cost: 4,
      cooldown: 4,
      power: 1.65,
      vfx: "burst",
      motion: "cinematic",
      desc: "A sweeping execution shot that marks the weakest enemy."
    },
    heal_pulse: {
      id: "heal_pulse",
      name: "Heal Pulse",
      slot: "A",
      target: "ally",
      mode: "heal",
      cost: 1,
      cooldown: 0,
      power: 1.25,
      vfx: "heal",
      motion: "cast",
      desc: "Restore a large amount of HP to one ally."
    },
    guard_bloom: {
      id: "guard_bloom",
      name: "Guard Bloom",
      slot: "B",
      target: "allyAll",
      mode: "shield",
      cost: 2,
      cooldown: 2,
      power: 1.0,
      vfx: "shield",
      motion: "cast",
      desc: "Create a protective bloom shield over the squad."
    },
    cleanse_stream: {
      id: "cleanse_stream",
      name: "Cleanse Stream",
      slot: "C",
      target: "ally",
      mode: "cleanse",
      cost: 2,
      cooldown: 1,
      power: 1.0,
      vfx: "heal",
      motion: "cast",
      desc: "Remove debuffs and restore a chunk of HP."
    },
    life_symphony: {
      id: "life_symphony",
      name: "Life Symphony",
      slot: "U",
      target: "allyAll",
      mode: "ultimateHeal",
      cost: 4,
      cooldown: 4,
      power: 1.5,
      vfx: "heal",
      motion: "cinematic",
      desc: "A full squad recovery with a strong regen finish."
    },
    void_pulse: {
      id: "void_pulse",
      name: "Void Pulse",
      slot: "A",
      target: "enemy",
      mode: "strike",
      cost: 1,
      cooldown: 0,
      power: 1.25,
      vfx: "burst",
      motion: "dash",
      desc: "A heavy void pulse that tears through armor."
    },
    gravity_brand: {
      id: "gravity_brand",
      name: "Gravity Brand",
      slot: "B",
      target: "enemy",
      mode: "debuff",
      cost: 2,
      cooldown: 1,
      power: 1.0,
      vfx: "burst",
      motion: "cast",
      desc: "Brand a target and slow its next turn."
    },
    nightfall_chain: {
      id: "nightfall_chain",
      name: "Nightfall Chain",
      slot: "C",
      target: "enemy",
      mode: "chain",
      cost: 2,
      cooldown: 1,
      power: 1.15,
      vfx: "bolt",
      motion: "zap",
      desc: "A chained astral strike that jumps once."
    },
    monarch_judgment: {
      id: "monarch_judgment",
      name: "Monarch Judgment",
      slot: "U",
      target: "enemyAll",
      mode: "ultimate",
      cost: 4,
      cooldown: 4,
      power: 1.8,
      vfx: "burst",
      motion: "cinematic",
      desc: "An apex void ritual that detonates all enemies at once."
    },
    enemy_burst: { id: "enemy_burst", name: "Burst Fire", slot: "A", target: "enemy", mode: "projectile", cost: 1, cooldown: 0, power: 1.0, vfx: "impact", motion: "shot", desc: "Enemy burst fire." },
    enemy_pressure: { id: "enemy_pressure", name: "Pressure Spray", slot: "B", target: "enemy", mode: "strike", cost: 1, cooldown: 1, power: 0.95, vfx: "slash", motion: "dash", desc: "Close pressure attack." },
    enemy_cover: { id: "enemy_cover", name: "Cover Matrix", slot: "C", target: "allyAll", mode: "shield", cost: 2, cooldown: 2, power: 0.9, vfx: "shield", motion: "cast", desc: "Enemy barrier." },
    enemy_laser: { id: "enemy_laser", name: "Laser Shot", slot: "A", target: "enemy", mode: "pierce", cost: 1, cooldown: 0, power: 1.1, vfx: "impact", motion: "shot", desc: "Precise laser." },
    enemy_chain: { id: "enemy_chain", name: "Chain Spark", slot: "B", target: "enemy", mode: "chain", cost: 2, cooldown: 1, power: 1.0, vfx: "bolt", motion: "zap", desc: "Chain spark." },
    enemy_shield: { id: "enemy_shield", name: "Shield Node", slot: "C", target: "allyAll", mode: "shield", cost: 2, cooldown: 1, power: 1.0, vfx: "shield", motion: "cast", desc: "Barrier node." },
    enemy_slash: { id: "enemy_slash", name: "Slash Run", slot: "A", target: "enemy", mode: "slash", cost: 1, cooldown: 0, power: 1.1, vfx: "slash", motion: "dash", desc: "Enemy dash slash." },
    enemy_mark: { id: "enemy_mark", name: "Mark Target", slot: "B", target: "enemy", mode: "debuff", cost: 1, cooldown: 1, power: 0.9, vfx: "impact", motion: "cast", desc: "Mark target." },
    enemy_strike: { id: "enemy_strike", name: "Rift Strike", slot: "C", target: "enemy", mode: "strike", cost: 2, cooldown: 1, power: 1.25, vfx: "burst", motion: "smash", desc: "Heavy strike." },
    enemy_void: { id: "enemy_void", name: "Void Spike", slot: "A", target: "enemy", mode: "pierce", cost: 1, cooldown: 0, power: 1.2, vfx: "burst", motion: "shot", desc: "Void spike." },
    enemy_brand: { id: "enemy_brand", name: "Dark Brand", slot: "B", target: "enemy", mode: "debuff", cost: 2, cooldown: 1, power: 1.0, vfx: "bolt", motion: "cast", desc: "Dark brand." },
    enemy_blast: { id: "enemy_blast", name: "Monolith Blast", slot: "C", target: "enemyAll", mode: "ultimate", cost: 4, cooldown: 4, power: 1.45, vfx: "burst", motion: "cinematic", desc: "Boss blast." }
  },
  stages: [
    {
      id: 1,
      name: "Harbor Neon",
      scene: "wet docks and skyline",
      enemyLineup: ["raider", "drone", "raider"],
      reward: { credits: 180, gems: 25, shards: { rin: 5, lyra: 3 } }
    },
    {
      id: 2,
      name: "Metro Stack",
      scene: "abandoned rail zone",
      enemyLineup: ["drone", "assassin", "raider"],
      reward: { credits: 240, gems: 30, shards: { gale: 4, mina: 3 } }
    },
    {
      id: 3,
      name: "Signal Core",
      scene: "holo tower interior",
      enemyLineup: ["drone", "assassin", "drone"],
      reward: { credits: 320, gems: 35, shards: { lyra: 5, yuna: 4 } }
    },
    {
      id: 4,
      name: "Skyline Gate",
      scene: "bridge under storm lights",
      enemyLineup: ["assassin", "raider", "warden"],
      reward: { credits: 420, gems: 48, shards: { gale: 5, mina: 4 } }
    },
    {
      id: 5,
      name: "Void Relay",
      scene: "central relay dome",
      enemyLineup: ["drone", "warden", "assassin"],
      reward: { credits: 560, gems: 60, shards: { yuna: 5, kuro: 5 } }
    },
    {
      id: 6,
      name: "Monarch Fall",
      scene: "boss arena",
      enemyLineup: ["warden", "assassin", "warden"],
      reward: { credits: 760, gems: 80, shards: { kuro: 8 } }
    },
    {
      id: 7,
      name: "Afterglow Circuit",
      scene: "pvp calibration",
      enemyLineup: ["drone", "raider", "assassin"],
      reward: { credits: 920, gems: 90, shards: { rin: 6, lyra: 4 } }
    },
    {
      id: 8,
      name: "Apex Rift",
      scene: "elite loop",
      enemyLineup: ["warden", "warden", "assassin"],
      reward: { credits: 1120, gems: 120, shards: { gale: 6, kuro: 8 } }
    }
  ],
  banners: [
    {
      id: "standard",
      name: "Standard Drop",
      featured: ["rin", "lyra", "mina"],
      desc: "Broad roster pool with one guaranteed rare every ten pulls.",
      rates: { N: 58, R: 30, SR: 10, SSR: 2 },
      costOne: { gems: 100, tickets: 1 },
      costTen: { gems: 900, tickets: 0 },
      pityAt: 60
    },
    {
      id: "void",
      name: "Void Monarch",
      featured: ["kuro", "gale", "yuna"],
      desc: "Featured SSR banner with boosted shard drops for void-themed units.",
      rates: { N: 55, R: 28, SR: 12, SSR: 5 },
      costOne: { gems: 120, tickets: 1 },
      costTen: { gems: 1000, tickets: 0 },
      pityAt: 50
    }
  ],
  synergies: [
    {
      id: "vanguard_chain",
      name: "Vanguard Chain",
      members: ["rin", "gale"],
      bonus: "Opening hit deals +15% damage and applies one extra stack of Focus."
    },
    {
      id: "aura_bloom",
      name: "Aura Bloom",
      members: ["mina", "gale"],
      bonus: "Shields from Mina are 20% stronger when Gale is on the squad."
    },
    {
      id: "data_void",
      name: "Data Void",
      members: ["lyra", "kuro"],
      bonus: "Hack and void skills grant one point of bonus mana after a takedown."
    },
    {
      id: "afterglow",
      name: "Afterglow",
      members: ["yuna", "rin", "lyra"],
      bonus: "Crits from the first action of a turn gain bonus splash damage."
    }
  ],
  pvpOpponents: [
    { name: "Saigon Rail", rank: 1140, mood: "tempo" },
    { name: "Delta Byte", rank: 1270, mood: "burst" },
    { name: "Redline 404", rank: 1360, mood: "control" },
    { name: "Echo Yard", rank: 1410, mood: "tank" },
    { name: "Iron Lotus", rank: 1500, mood: "assassin" }
  ]
};
